spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: admin-user
    password: VGZgv6tDAbrBcJn
    url: jdbc:sqlserver://timetable-project.database.windows.net:1433;database=TimetableDB;user=admin-user@timetable-project;password=VGZgv6tDAbrBcJn;encrypt=true;trustServerCertificate=true;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
