spring:
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
